(part "GG0402052R542P"
    (packageRef "DIONC1006X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "581-GG0402052R542P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KYOCERA-AVX/GG0402052R542P?qs=AQlKX63v8RvyHtzj%2F7p1Bg%3D%3D")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "GG0402052R542P")
    (property "Description" "ESD Suppressors / TVS Diodes SMP Diode 0402 5vdc 2.5 pf <12v clamp@1a")
    (property "Datasheet_Link" "")
    (property "symbolName1" "GG0402052R542P")
)
