(part "MC14051BDR2G"
    (packageRef "SOIC127P600X175-16N")
    (interface
        (port "1" (symbPinId 1) (portName "X4") (portType INOUT))
        (port "2" (symbPinId 2) (portName "X6") (portType INOUT))
        (port "3" (symbPinId 3) (portName "X") (portType INOUT))
        (port "4" (symbPinId 4) (portName "X7") (portType INOUT))
        (port "5" (symbPinId 5) (portName "X5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "INH") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VEE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VSS") (portType INOUT))
        (port "9" (symbPinId 9) (portName "C") (portType INOUT))
        (port "10" (symbPinId 10) (portName "B") (portType INOUT))
        (port "11" (symbPinId 11) (portName "A") (portType INOUT))
        (port "12" (symbPinId 12) (portName "X3") (portType INOUT))
        (port "13" (symbPinId 13) (portName "X0") (portType INOUT))
        (port "14" (symbPinId 14) (portName "X1") (portType INOUT))
        (port "15" (symbPinId 15) (portName "X2") (portType INOUT))
        (port "16" (symbPinId 16) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "863-MC14051BDR2G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/MC14051BDR2G?qs=g2rIOKKlpoZiRT%252Bz5I%252B8eg%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MC14051BDR2G")
    (property "Description" "Low-noise - 12 nV/sqrt.Cycle, f <= 1.0 kHz Typical; For 4PDT Switch, See MC14551B; Switch Function is Break Before Make; Supply Voltage Range = 3.0 Vdc to 18 Vdc; Analog Voltage Range (VDD - VEE) = 3.0 to 18 V Note: VEE must be <= VSS; Triple Diode Protection on Control Inputs; For Lower RON, Use the HC4051, HC4052, or HC4053 High-Speed CMOS Devices; Linearized Transfer Characteristics; Pin-for-Pin Replacement for CD4051, CD4052, and CD4053; Pb-Free Packages are Available*")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/MC14051B-D.PDF")
    (property "symbolName1" "MC14051BDR2G")
)
